### ISSUE TITLE
Method name does not match javadoc description

### ISSUE THREAD

**Issue by awoods** [UW-Madison-Library/ocfl-java#2]
Based on the javadocs and the method parameters, it would seem that this method should be named something like `putFile()` instead of `getFile()`.

https://github.com/UW-Madison-Library/ocfl-java/blob/31129b8ccdd1b9f52a9cbfcfdb6353ec90944e47/ocfl-java-api/src/main/java/edu/wisc/library/ocfl/api/OcflObjectReader.java#L41

**Comment by pwinckles** [comment]
It's _getting_ a file out of an OCFL object. I'm open to renaming pretty much anything, but I don't think `put` is a good fit here. In my mind, I _put_ files into the repository and _get_ them out.

**Comment by awoods** [comment]
Thanks for clarifying. Maybe the minor update in the javadoc from:
```
Writes a specific file to the given destinationPath
```
to:
```
Writes a specific file to the given destinationPath outside of the OCFL Storage Root
```
..would have corrected my assumptions.

**Comment by pwinckles** [comment]
Thanks, I updated the text. Let me know if you find anything else that's unclear.
