### ISSUE TITLE
configurable behavior on unknown extensions

### ISSUE THREAD

**Issue by pwinckles** [UW-Madison-Library/ocfl-java#26]
Allow users to configure what they want to happen when unsupported extensions are encountered:

1. Fail on unknown repo extensions
2. Warn on unknown repo extensions
3. Fail on unknown object extensions
4. Warn on unknown object extensions

**Comment by bcail** [comment]
Would these options affect storage layout extensions?

For non-storage-layout extensions, I could see an option of "fail, but allow an override" being useful.

**Comment by pwinckles** [comment]
@bcail Can you elaborate on what you mean?

**Comment by bcail** [comment]
Sure. For safety, I could the failure option being helpful - if you don't understand something, just fail. But, there could be a situation where the unknown extension is harmless, so I want to override the default failure mode to just do the operation anyway.

**Comment by pwinckles** [comment]
resolved with https://github.com/UW-Madison-Library/ocfl-java/commit/779e60eb5bf9e9231a2b61e7114cf6ce293191e1
